Repository theoraccoon/amby-craft-be, pull requests merged in 2025-04, with the labels that each got.

#12 feat(google-auth): scaffold module with CQRS structure for Google SSO
  package-lock.json
  package.json
  src/auth/google/commands/handleGoogleLogin.command.ts
  src/auth/google/google-auth.controller.ts
  src/auth/google/google-auth.module.ts
  src/auth/google/google-auth.service.ts
  src/auth/google/handlers/handleGoogleLogin.handler.ts
  src/auth/google/queries/getUserByGoogleId.query.ts
  src/auth/google/strategies/google.strategy.ts
Labels: enhancement

#15 feat(auth): implement Google OAuth strategy with unit test
  CHANGELOG.md
  src/auth/google/commands/handleGoogleLogin.command.ts
  src/auth/google/strategies/google.strategy.ts
  test/google.strategy.spec.ts
Labels: feature

#16 chore(ci): refactored pre commit hooks to support linting operations before commiting and pushing to github
  .husky/commit-msg
  .husky/pre-commit
Labels: enhancement

#20 feat: add other models
  prisma/migrations/20250428160346_add_course_lesson_lessontype_content_models/migration.sql
  prisma/schema.prisma
  src/config/constants.ts
Labels: enhancement

#31 chore(ci): dangerfile modification to exclude project.json & project-lock.json files
  dangerfile.js
Labels: enhancement

#37 feat(google-auth): added prisma module and also installed bcrypt pack…
  package-lock.json
  package.json
  src/prisma/prisma.module.ts
  src/prisma/prisma.service.ts
  test/google.strategy.spec.ts
  tsconfig.json
Labels: feature

#39 feat(google-auth): implemented validate oauth login command
  eslint.config.mjs
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/google/commands/handleGoogleLogin.command.ts
  src/auth/google/commands/validate-oauth-login.command.ts
  src/auth/google/handlers/handleGoogleLogin.handler.ts
  src/auth/google/queries/getUserByGoogleId.query.ts
  src/auth/google/strategies/google.strategy.ts
  src/config/constants.ts
Labels: feature

#41 feat(google-auth): implemented google auth controller and token service
  src/auth/google/google-auth.controller.ts
  src/auth/google/services/token.service.ts
Labels: feature

#42 feat(google-auth): implemented google authentication with jwt accesst…
  src/app.module.ts
  src/auth/google/google-auth.module.ts
  src/auth/google/handlers/validate-oauth-login.handler.ts
Labels: feature

#43 chore: house cleaning using constants
  src/app.controller.ts
  src/app.service.ts
  src/config/constants.ts
  src/config/swagger.config.ts
  src/main.ts
  tsconfig.json
Labels: chore

#44 feat(course): create course crud cqrs folder structure
  src/course/commands/create-course.command.ts
  src/course/commands/delete-course.command.ts
  src/course/commands/handlers/create-course.handler.ts
  src/course/commands/handlers/delete-course.handler.ts
  src/course/commands/handlers/update-course.handler.ts
  src/course/commands/update-course.command.ts
  src/course/course.controller.ts
  src/course/dto/create-course.dto.ts
  src/course/dto/update-course.dto.ts
  src/course/queries/get-all-courses.query.ts
  src/course/queries/get-course-by-id.query.ts
  src/course/queries/handlers/get-all-courses.handler.ts
  src/course/queries/handlers/get-course-by-id.handler.ts
  src/course/services/course.service.ts
Labels: feature

#45 chore: in house cleaning
  .prettierrc
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.service.ts
  src/auth/google/commands/validate-oauth-login.command.ts
  src/auth/google/google-auth.controller.ts
  src/auth/google/google-auth.module.ts
  src/auth/google/handlers/validate-oauth-login.handler.ts
  src/auth/google/services/google-auth.service.ts
  src/auth/google/services/token.service.ts
  src/auth/strategies/google.strategy.ts
  src/config/constants.ts
  src/config/swagger.config.ts
  src/database/database.module.ts
  src/main.ts
  src/prisma/prisma.module.ts
  src/types/fastify.d.ts
  test/app.e2e-spec.ts
  tsconfig.json
Labels: enhancement, api

#56 chore: add user crud and interceptors
  eslint.config.mjs
  package-lock.json
  package.json
  src/auth/dto/create-user.dto.ts
  src/auth/dto/login.dto.ts
  src/auth/dto/update-user.dto.ts
  src/common/dto/api-response.dto.ts
  src/common/interceptors/transform.interceptor.ts
  src/common/query/common.query.ts
  src/helper/api-response-example.ts
  src/main.ts
  src/users/dto/create-user.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: enhancement, feature

#57 chore(cleanups): minor clean ups to conform with the prettierrc & eslint configurations
  src/app.module.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: chore, type:enhancement, area:api
