Repository theoraccoon/amby-craft-be, pull requests merged in 2025-05, with the labels that each got.

#66 chore(in-house-cleaning): minor cleaning to resolve linting, renamed primsa dir to database
  package.json
  src/auth/google/handlers/validate-oauth-login.handler.ts
  src/auth/google/services/token.service.ts
  src/common/dto/api-response.dto.ts
  src/common/interceptors/transform.interceptor.ts
  src/database/database.module.ts
  src/database/database.service.ts
  src/helper/api-response-example.ts
  src/main.ts
  src/prisma/prisma.module.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
  tsconfig.json
Labels: type:enhancement, area:api

#70 Feat/auth logic
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/types/index.ts
  src/config/constants.ts
Labels: enhancement

#76 Chore/updated text literals with constants
  src/auth/auth.service.ts
  src/auth/google/google-auth.module.ts
  src/config/constants.ts
Labels: chore

#77 Chore/cleanups
  package-lock.json
  package.json
  src/auth/google/handlers/validate-oauth-login.handler.ts
  src/auth/google/services/token.service.ts
  src/common/interceptors/response.interceptor.ts
  src/common/query/common.query.ts
  src/database/database.module.ts
  src/main.ts
  src/users/users.module.ts
  src/users/users.service.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.json
Labels: type:enhancement, area:api

#78 chore(test): reorganized unit tests and reconfigured entry points for tests
  docker-compose.yml
  package.json
  prisma/schema.prisma
  src/common/dtos/api-response.dto.ts
  src/users/users.service.ts
  test/jest-e2e.json
  test/users/users.controller.spec.ts
  test/users/users.service.spec.ts
Labels: type:enhancement, area:api

#80 feat(course): course model and dto implementation for endpoints
  prisma/schema.prisma
  src/course/dto/create-course.dto.ts
Labels: type:enhancement, area:api

#82 feat(course): create course service, command, handler, queries and controller implementation
  src/modules/block/block.controller.ts
  src/modules/block/commands/create-block.command.ts
  src/modules/block/commands/delete-block.command.ts
  src/modules/block/commands/handlers/create-block.handler.ts
  src/modules/block/commands/handlers/delete-block.handler.ts
  src/modules/block/commands/handlers/update-block.handler.ts
  src/modules/block/commands/update-block.command.ts
  src/modules/block/dto/create-block.dto.ts
  src/modules/block/dto/update-block.dto.ts
  src/modules/block/queries/get-all-blocks.query.ts
  src/modules/block/queries/get-block-by-id.query.ts
  src/modules/block/queries/handlers/get-all-blocks.handler.ts
  src/modules/block/queries/handlers/get-block-by-id.handler.ts
  src/modules/block/services/block.service.ts
  src/modules/course/commands/create-course.command.ts
  src/modules/course/commands/delete-course.command.ts
  src/modules/course/commands/handlers/create-course.handler.ts
  src/modules/course/commands/handlers/delete-course.handler.ts
  src/modules/course/commands/handlers/update-course.handler.ts
  src/modules/course/commands/update-course.command.ts
  src/modules/course/course.controller.ts
  src/modules/course/course.module.ts
  src/modules/course/dto/create-course.dto.ts
  src/modules/course/dto/update-course.dto.ts
  src/modules/course/queries/get-all-courses.query.ts
  src/modules/course/queries/get-course-by-id.query.ts
  src/modules/course/queries/handlers/get-all-courses.handler.ts
  src/modules/course/queries/handlers/get-course-by-id.handler.ts
  src/modules/course/services/course.service.ts
  src/modules/lesson/commands/create-lesson.command.ts
  src/modules/lesson/commands/delete-lesson.command.ts
  src/modules/lesson/commands/handlers/create-lesson.handler.ts
  src/modules/lesson/commands/handlers/delete-lesson.handler.ts
  src/modules/lesson/commands/handlers/update-lesson.handler.ts
  src/modules/lesson/commands/update-lesson.command.ts
  src/modules/lesson/dto/create-lesson.dto.ts
  src/modules/lesson/dto/update-lesson.dto.ts
  src/modules/lesson/lesson.controller.ts
  src/modules/lesson/queries/get-all-lessons.query.ts
  src/modules/lesson/queries/get-lesson-by-id.query.ts
  src/modules/lesson/queries/handlers/get-all-lessons.handler.ts
  src/modules/lesson/queries/handlers/get-lesson-by-id.handler.ts
  src/modules/lesson/services/lesson.service.ts
Labels: type:enhancement, area:api

#83 chore(clean ups): minor formatting clean ups and linting
  src/auth/dto/create-user.dto.ts
  src/auth/dto/login.dto.ts
Labels: type:enhancement, area:api

#84 chore(course): course creation clean ups
  .dockerignore
  .gitignore
  Dockerfile
  docker-compose.yml
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/google/google-auth.controller.ts
  src/auth/google/google-auth.module.ts
  src/auth/strategies/google.strategy.ts
  src/modules/course/commands/create-course.command.ts
  src/modules/course/commands/handlers/create-course.handler.ts
  src/modules/course/course.controller.ts
  src/modules/course/course.module.ts
  src/modules/course/dto/create-course.dto.ts
  src/modules/course/services/course.service.ts
Labels: type:enhancement, area:api

#87 feat(lesson): add and view a lesson implementation
  src/app.module.ts
  src/modules/course/courses.controller.ts
  src/modules/course/courses.module.ts
  src/modules/lesson/commands/create-lesson.command.ts
  src/modules/lesson/commands/handlers/create-lesson.handler.ts
  src/modules/lesson/dto/create-lesson.dto.ts
  src/modules/lesson/lesson.controller.ts
  src/modules/lesson/lesson.module.ts
  src/modules/lesson/queries/get-all-lessons.query.ts
  src/modules/lesson/queries/get-lesson-by-id.query.ts
  src/modules/lesson/queries/get-lesson.query.ts
  src/modules/lesson/queries/handlers/get-all-lessons.handler.ts
  src/modules/lesson/queries/handlers/get-lesson-by-id.handler.ts
  src/modules/lesson/queries/handlers/get-lesson.handler.ts
  tsconfig.json
Labels: type:enhancement, area:api

#86 chore(google-auth): moved google auth to modules directory
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/strategies/google.strategy.ts
  src/modules/auth/google/commands/validate-oauth-login.command.ts
  src/modules/auth/google/google-auth.controller.ts
  src/modules/auth/google/google-auth.module.ts
  src/modules/auth/google/handlers/validate-oauth-login.handler.ts
  src/modules/auth/google/services/google-auth.service.ts
Labels: type:enhancement, area:api, type:chore

#88 chore(moved): email auth to basic under auth
  src/app.module.ts
  src/modules/auth/basic/auth.controller.ts
  src/modules/auth/basic/auth.module.ts
  src/modules/auth/basic/auth.service.ts
  src/modules/auth/dto/create-user.dto.ts
  src/modules/auth/dto/login.dto.ts
  src/modules/auth/dto/update-user.dto.ts
  src/modules/auth/google/google-auth.module.ts
  src/modules/auth/google/handlers/validate-oauth-login.handler.ts
  src/modules/auth/google/services/token.service.ts
  src/modules/auth/strategies/google.strategy.ts
  src/modules/auth/types/index.ts
  src/users/users.service.ts
Labels: type:enhancement, type:chore

#90 feat(lang): installed i18n package for language translation
  nest-cli.json
  package-lock.json
  package.json
  src/app.module.ts
  src/config/constants.ts
  src/config/lang/de.json
  src/config/lang/en.json
  tsconfig.json
Labels: feature

#92 feat(error-handling): clean ups and testing
  .gitignore
  Dockerfile
  docker-compose-dev.yml
  docker-compose-prod.yml
  docker-compose.yml
  package.json
  prisma/migrations/20250417093953_init/migration.sql
  prisma/migrations/20250423143146_add_identifier_to_roles/migration.sql
  prisma/migrations/20250428160346_add_course_lesson_lessontype_content_models/migration.sql
  prisma/migrations/20250429103951_refresh_token_user/migration.sql
  prisma/migrations/20250506160249_init/migration.sql
  prisma/migrations/migration_lock.toml
  src/common/dtos/api-response.dto.ts
  src/common/filters/http-exception.filter.ts
  src/database/database.service.ts
  src/modules/course/commands/handlers/create-course.handler.ts
  src/modules/course/courses.controller.ts
  src/modules/course/dto/create-course.dto.ts
  src/modules/lesson/lesson.controller.ts
  src/modules/lesson/queries/handlers/get-all-lessons.handler.ts
  start-docker.ps1
Labels: type:enhancement, area:api

#93 chore(lang): converted en.json in english to de.json(german)
  src/config/lang/de.json
Labels: chore

#94 chore(i18n): update constants
  src/app.module.ts
  src/config/constants.ts
Labels: chore

#95 chore(restructure): restructure project modules and add user management functionality
  src/app.module.ts
  src/app.service.ts
  src/common/config/constants.ts
  src/common/config/env.ts
  src/common/config/lang/de.json
  src/common/config/lang/en.json
  src/common/config/swagger.config.ts
  src/common/database/database.module.ts
  src/common/database/database.service.ts
  src/main.ts
  src/modules/auth/basic/auth.module.ts
  src/modules/auth/basic/auth.service.ts
  src/modules/auth/google/google-auth.controller.ts
  src/modules/auth/google/handlers/validate-oauth-login.handler.ts
  src/modules/auth/google/services/token.service.ts
  src/modules/course/commands/handlers/create-course.handler.ts
  src/modules/course/queries/handlers/get-course-by-id.handler.ts
  src/modules/lesson/commands/handlers/create-lesson.handler.ts
  src/modules/lesson/queries/handlers/get-all-lessons.handler.ts
  src/modules/lesson/queries/handlers/get-lesson.handler.ts
  src/modules/lesson/services/lesson.service.ts
  src/modules/users/entities/user.entity.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
  test/users/users.controller.spec.ts
  test/users/users.service.spec.ts
Labels: area:api, type:chore

#97 feat(jwt-startegy): implement jwt strategy and jwt auth guard
  eslint.config.mjs
  src/config/config.schema.ts
  src/modules/auth/guards/jwt-auth.guard.ts
  src/modules/auth/strategies/jwt.strategy.ts
Labels: feature

#99 feat(block): implement create and get block functionality
  src/modules/block/block.controller.ts
  src/modules/block/commands/create-block.command.ts
  src/modules/block/commands/handlers/create-block.handler.ts
  src/modules/block/dto/create-block.dto.ts
  src/modules/block/queries/get-all-blocks.query.ts
  src/modules/block/queries/get-block-by-id.query.ts
  src/modules/block/queries/handlers/get-all-blocks.handler.ts
  src/modules/block/queries/handlers/get-block-by-id.handler.ts
  src/modules/block/services/block.service.ts
Labels: type:enhancement, area:api

#101 feat(block): add BlockModule with CQRS handlers and controller
  docker-compose-dev.yml
  src/app.module.ts
  src/modules/block/block.module.ts
Labels: type:enhancement, type:chore, area:api

#102 feat(prisma): add migration and seeding functions for roles and users
  package.json
  prisma/migrations/20250512133048_init/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
Labels: type:feature, area:api

#100 71 feature create user sign out
  src/modules/auth/basic/auth.controller.ts
  src/modules/auth/basic/auth.module.ts
  src/modules/auth/basic/auth.service.ts
  src/modules/auth/basic/commands/signout.command.ts
  src/modules/auth/basic/handlers/signout.handler.ts
Labels: type:enhancement, type:feature

#103 feat(block): add endpoint to retrieve all blocks
  src/modules/block/block.controller.ts
  src/modules/course/courses.controller.ts
Labels: type:enhancement, type:feature, area:api

#104 fix(constants): standardize ping and pong responses to lowercase
  src/common/config/constants.ts
Labels: type:enhancement, type:chore, area:api

#105 Feat/implement redirect with cookies
  .gitignore
  eslint.config.mjs
  prisma/schema.prisma
  src/common/config/constants.ts
  src/main.ts
  src/modules/auth/google/google-auth.controller.ts
  src/modules/auth/google/google-auth.module.ts
  src/modules/auth/google/handlers/validate-oauth-login.handler.ts
  src/modules/auth/google/services/google-auth.service.ts
  src/modules/auth/strategies/google.strategy.ts
Labels: type:feature

#106 feat(decorator-authguard): implement-decorator-current-user-and-auth-…
  eslint.config.mjs
  prisma/schema.prisma
  src/common/config/constants.ts
  src/common/decorators/current-user.decorator.ts
  src/modules/auth/basic/auth.service.ts
  src/modules/auth/google/services/token.service.ts
  src/modules/auth/strategies/jwt.strategy.ts
  src/modules/course/courses.controller.ts
  src/modules/course/queries/handlers/get-course-by-id.handler.ts
  src/modules/lesson/lesson.controller.ts
Labels: type:feature

#110 chore: refactor basic auth to cqrs work handlers
  src/modules/auth/basic/auth.controller.ts
  src/modules/auth/basic/auth.module.ts
  src/modules/auth/basic/handlers/refresh-token.handler.ts
  src/modules/auth/basic/queries/refresh-token.ts
Labels: type:enhancement

#111 fix(prettier): update trailingComma setting to 'es5' and ensure consistent endOfLine
  .prettierrc
Labels: type:chore, area:api

#114 refactor: course retrieval in GetCourseHandler
  src/modules/course/queries/handlers/get-course-by-id.handler.ts
Labels: type:enhancement, area:api

#116 fix: prettier configuration and add missing commas
  .prettierrc
  src/modules/block/block.controller.ts
  src/modules/lesson/commands/update-lesson.command.ts
  src/modules/lesson/lesson.controller.ts
Labels: type:enhancement, type:chore, area:api

#117 chore(auth): update jwt payload and removed config.schema
  src/config/config.schema.ts
  src/modules/auth/basic/services/auth.service.ts
  src/modules/auth/strategies/google.strategy.ts
  src/modules/auth/strategies/jwt.strategy.ts
  src/modules/auth/types/index.ts
Labels: type:chore

#120 feat(blocks): implement update bloks endpoint
  src/modules/block/block.controller.ts
  src/modules/block/block.module.ts
  src/modules/block/commands/handlers/update-block.handler.ts
  src/modules/block/commands/update-block.command.ts
  src/modules/block/dto/update-block.dto.ts
Labels: type:feature, area:api

#121 feat(auth): auth basic cqrs
  src/modules/auth/basic/auth.controller.ts
  src/modules/auth/basic/commands/signout.command.ts
  src/modules/auth/basic/services/auth.service.ts
  src/modules/auth/google/google-auth.controller.ts
  src/modules/auth/strategies/google.strategy.ts
  src/modules/course/courses.controller.ts
  src/modules/course/queries/get-course-by-id.query.ts
Labels: type:enhancement

#127 refactor(auth) authentication module and implement Google login features
  Dockerfile
  docker-compose-prod.yml
  package-lock.json
  package.json
  src/app.module.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/basic/auth.controller.ts
  src/modules/auth/basic/commands/handlers/register.handler.ts
  src/modules/auth/basic/commands/signout.command.ts
  src/modules/auth/commands/google-auth.command.ts
  src/modules/auth/commands/handlers/google-auth-command.handler.ts
  src/modules/auth/commands/handlers/refresh-token-command.handler.ts
  src/modules/auth/commands/handlers/register-user.handler.ts
  src/modules/auth/commands/handlers/signout.handler.ts
  src/modules/auth/commands/refresh-token.command.ts
  src/modules/auth/commands/register-user.command.ts
  src/modules/auth/commands/signout.command.ts
  src/modules/auth/google/services/google-auth.service.ts
  src/modules/auth/guards/jwt-refresh-auth.guard.ts
  src/modules/auth/queries/handlers/login.handler.ts
  src/modules/auth/queries/handlers/refresh-token.handler.ts
  src/modules/auth/queries/login.query.ts
  src/modules/auth/queries/refresh-token.ts
  src/modules/auth/services/auth.service.ts
  src/modules/auth/strategies/google.strategy.ts
  src/modules/auth/strategies/jwt-refresh.strategy.ts
  src/modules/auth/strategies/jwt.strategy.ts
  src/modules/auth/types/index.ts
Labels: type:enhancement, type:feature, type:chore, area:api

#136 refactor(authentication) improve flow
  src/app.module.ts
  src/common/config/constants.ts
  src/common/interceptors/exclude-fields.interceptor.ts
  src/common/query/common.query.ts
  src/common/utils/exclude.ts
  src/main.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/commands/handlers/google-auth-command.handler.ts
  src/modules/auth/commands/handlers/index.ts
  src/modules/auth/commands/handlers/login-user-command.handler.ts
  src/modules/auth/commands/handlers/refresh-token-command.handler.ts
  src/modules/auth/commands/handlers/register-user.handler.ts
  src/modules/auth/commands/handlers/signout.handler.ts
  src/modules/auth/commands/login-user.command.ts
  src/modules/auth/commands/refresh-token.command.ts
  src/modules/auth/dto/create-user.dto.ts
  src/modules/auth/dto/login.dto.ts
  src/modules/auth/dto/refresh-token.dto.ts
  src/modules/auth/google/commands/validate-oauth-login.command.ts
  src/modules/auth/google/google-auth.controller.ts
  src/modules/auth/google/google-auth.module.ts
  src/modules/auth/google/handlers/validate-oauth-login.handler.ts
  src/modules/auth/google/services/google-auth.service.ts
  src/modules/auth/google/services/token.service.ts
  src/modules/auth/queries/handlers/login.handler.ts
  src/modules/auth/queries/handlers/refresh-token.handler.ts
  src/modules/auth/queries/login.query.ts
  src/modules/auth/queries/refresh-token.ts
  src/modules/auth/services/auth.service.ts
  src/modules/auth/services/token.service.ts
  src/modules/auth/strategies/google.strategy.ts
Labels: type:chore, area:api

#137 refactor(auth) process and improve session management
  docker-compose-prod.yml
  src/common/utils/auth.utils.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/commands/handlers/google-auth-command.handler.ts
  src/modules/auth/commands/handlers/index.ts
  src/modules/auth/commands/handlers/logout-user-command.handler.ts
  src/modules/auth/commands/logout-user.command.ts
  src/modules/auth/strategies/google.strategy.ts
Labels: type:enhancement, area:api

#140 chore(google): add prompt select-account
  src/modules/auth/strategies/google.strategy.ts
Labels: type:chore
